name: Cypress Tests with Allure Report

on:
  push:
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with Allure
        run: |
          npx cypress run --env allure=true
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy-report:
    needs: cypress-run
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: allurereport
          folder: allure-report
